### ISSUE TITLE
would it be possible to edit the 'otter'-buffer with the excellent nvim-R- package, so that interactive changes could be saved back to the code chunks

### ISSUE THREAD

**Issue by emilBeBri** [jmbuhr/otter.nvim#10]
Hi so this is above my skill level to implement my self, but what I really mis about Sublime Text is that I had a plugin that could just send lines of codes to tmux. This meant that I would interatively edit code chunks in a quarto document, because it didn't what type of file it was. 

Now I'm using nvim-R  for my R scripts, which is completely amazing. But it does not work in code chunks in a quarto document, so I have to copy back and forth when polising something. 

So I was thinking if it is possible to edit the hidden buffer, which I guess is an R file type, so that I would edit that with nvim-R and a terminal, and then changes saved would go back to the code chunks?

As you can hear,  I do not have much knowledge about what's going on under the hood. But I'm hoping it would be possible?

**Comment by jmbuhr** [comment]
No need to edit the hidden buffer for that. In the [kickstarter configuration](https://github.com/jmbuhr/quarto-nvim-kickstarter) I included and configured the plugin [vim-slime](https://github.com/jpalardy/vim-slime) that can send chunks of code to many places, including tmux (which I use as well) and the integrated neovim terminal (which is what I configured for the kickstarter repo). I am working on a video to show the features, which is supposed to go live after I finished the getting started section on Neovim for the quarto website, but I have now put it already out there as unlisted. Once it has finished processing on YouTube's servers in around 30 minutes, you can watch it [here](https://youtu.be/3sj7clNowlA). Let me know if you have any suggestions!

**Comment by jmbuhr** [comment]
I use it for quarto code chunks see https://github.com/jmbuhr/quarto-nvim-kickstarter/blob/main/ftplugin/markdown.lua, but also in plain R or python chunks by adding these comments to designate code chunks: https://github.com/jmbuhr/quarto-nvim-kickstarter/blob/main/ftplugin/r.lua

**Comment by jmbuhr** [comment]
If you want to use tmux instead of the integrated neovim terminal you can swap the comments in these lines:

https://github.com/jmbuhr/quarto-nvim-kickstarter/blob/38a04c7e3893fc6a92d83c2ec4235ddcfa335144/lua/config/global.lua#L69-L78

**Comment by emilBeBri** [comment]
That sounds great I'll take a look at it in the beginning of next week! Thank you for all your hard work.
