### ISSUE TITLE
Otter not loading unless save and quit neovim and reopen buffer

### ISSUE THREAD

**Issue by adam-coates** [jmbuhr/otter.nvim#108]
As the title says. 

If I make a new quarto document and create code chunks (without saving) otter doesn't show cmp suggestions. 

If I save multiple times similarly otter still doesn't show code completions. Only after I quit neovim and load the same quarto document does cmp work for all code chunks. 

However, if I created say an .r or .sh or .py file I get full suggestions without having to quit nvim first. 

I understand in otters use case that saving the buffer first would trigger the cmp right? But I am not entirely sure why I have to quit nvim and reopen the file? Perhaps soemone can help. For example, it almost seems like otters hidden buffers are only being created after saving and then quitting neovim, is there a way to debug which hidden buffers are created and when? Thanks in advance!

**Comment by adam-coates** [comment]
Okay so I have just seen that with `:ls!` you can get a list of buffers (hidden ones too). 
To refine this issue further. 

When a quarto document is made and an r chunk is added the `:ls!` output is the following: 

`:ls!
  1 %a + "~/test.qmd"                   line 2
  2u h   "[Scratch]"                    line 0
  3u a-  "NvimTree_1"                   line 0
  4u h   "[Scratch]"                    line 0
`

However, after quitting and reopening neovim the following is the output: 
`
:ls!
  1 %a   "~/test.qmd"                   line 2
  2u h   "[Scratch]"                    line 0
  4u h   "~/test.qmd.otter.R"           line 0
  5u a-  "NvimTree_1"                   line 0
`

Therefore, my suspicion was right above. It seems otter is only creating the hidden buffer after saving and then quitting nvim. Question is, is this normal behaviour and if not is there additional diagnostics I could perform. Thanks again!

**Comment by jmbuhr** [comment]
No need to quit and re-opend, just `:QuartoActivate` (or `otter.activate()`, but quarto also sets the keybindings) when you add a new language to your document. Otter has no way of knowing that you just added an R chunk if the document contained no code when it was first activated.

**Comment by adam-coates** [comment]
Hi yes, this makes sense. Apologies for my stupidity and not reading properly the documentation, this is my own ignorance. Its really true that generally 9 times out of 10 reading the documentation fixes it 😂. 
Thanks for a great plugin and for your patience.
