### ISSUE TITLE
Failed to run diagnostics with lintr

### ISSUE THREAD

**Issue by stefanocoretta** [jmbuhr/otter.nvim#116]
Hi! This is the same as https://github.com/quarto-dev/quarto-nvim/issues/84. I set `write_to_disk = true` but I am still getting the `Failed to run diagnostics` error with R code chunks in qmd files.

My config is here if it helps: https://github.com/stefanocoretta/kickstart-modular.nvim

🦦🤔🤷‍♂️

**Comment by jmbuhr** [comment]
Same linter? What's the full message?

**Comment by stefanocoretta** [comment]
Yes, same linter (lintr). Here's the full message :) 

<img width="1428" alt="Screenshot 2024-04-09 at 10 39 41" src="https://github.com/jmbuhr/otter.nvim/assets/6429302/b5bfb461-7416-4223-b829-28d78b2490c8">

**Comment by jmbuhr** [comment]
Found the issue. with the `config.buffer.write_to_disk` option enabled, we only write out the file on save, but lintr doesn't refresh afterwards. If you save the file and then activate otter (e..g via QuartoActivate)  it should work.

But I'll see if I can make it work out of the box!

**Comment by stefanocoretta** [comment]
Fantastic thank you! 🦦 🥰

**Comment by stefanocoretta** [comment]
Just a quick follow up, I set `write_to_disk = false` and changed my `.lintr` file to this and now linting works

```
linters: all_linters(
    object_length_linter = NULL,
    object_name_linter = NULL
  )
```

**Comment by jmbuhr** [comment]
Yes, for some reason it's only some linters of lintr that require a file on disk (no idea why).
