### ISSUE TITLE
[bug]ask format eat some additional lines

### ISSUE THREAD

**Issue by sidkang** [jmbuhr/otter.nvim#130]
thanks for with great plugin, which makes working with notebooks in nvim so much better. 

I happen to notice some lines is eaten when using the ask_format, I'm using otter with pyright and ruff-lsp server. Having tried with a minimal config on the astronvim pack, but it still remains.

### original
````
```python
print("first line")



print("2nd line")
```

## Header1

```python
print("3rd line.")



print("4th line.")
```

```python
print("5th line.")
```
````

### after ask format in the first code cell

It seems the '```' and 'header' is gone

````
```python
print("first line")


print("2nd line")

```python
print("3rd line.")



print("4th line.")
```

```python
print("5th line.")
```

````

### after ask format in the 2nd code cell

the '```' is gone.

````
```python
print("first line")



print("2nd line")
```

## Header1

```python
print("3rd line.")


print("4th line.")

```python
print("5th line.")
```

````

**Comment by jmbuhr** [comment]
Looks like https://github.com/jmbuhr/otter.nvim/issues/87#issuecomment-1937646958 is back, I'll investigate!

**Comment by jmbuhr** [comment]
In the process of rewriting how otter.nvim operates I (temporarily) removed the ability to handle formatting to make everything else much cleaner (see https://github.com/jmbuhr/otter.nvim?tab=readme-ov-file#otternvim and https://github.com/jmbuhr/otter.nvim?tab=readme-ov-file#current-limitations). I will revisit this properly in the future, but for now I recommend external plugins for formatting. Specifically conform.nvim works super well for me, here is my config: https://github.com/jmbuhr/quarto-nvim-kickstarter/blob/382b050e13eada7180ad048842386be37e820660/lua/plugins/editing.lua#L29-L81
