### ISSUE TITLE
Handle buffers without active raft more gracefully or provide a way to check whether a raft is registered

### ISSUE THREAD

**Issue by kmoschcau** [jmbuhr/otter.nvim#135]
When I for example run `otter.ask_hover()` in a buffer where `otter.activate()` wasn't run, I get the following error:
```
E5108: Error executing lua: ...u/.local/share/nvim/lazy/otter.nvim/lua/otter/keeper.lua:381: attempt to index a nil value
stack traceback:
        ...u/.local/share/nvim/lazy/otter.nvim/lua/otter/keeper.lua:381: in function 'send_request'
        ...cau/.local/share/nvim/lazy/otter.nvim/lua/otter/init.lua:326: in function 'ask_hover'
```

I can fix this with an `xpcall` for now, but it would be nice, if I could check whether otter was activated in the current buffer in my keymap instead.

**Comment by jmbuhr** [comment]
Thanks for the report, that's indeed something we should address.

**Comment by jmbuhr** [comment]
Todo:

- [ ] handle `nil` in `send_request` more gracefully
- [ ] automatically use fallback function of `ask_` functions if otter is not activated
- [ ] provide easier access and document checking if otter is activated for current buffer

**Comment by jmbuhr** [comment]
With https://github.com/jmbuhr/otter.nvim/pull/136 it does both now. If no otters are attached to the current buffer the fallback is used automatically and you can manually check if otter is activated with the `otter.keeper.has_raft(bufnr)` function.
