### ISSUE TITLE
Installing quarto in Noevim produces multiple errors.

### ISSUE THREAD

**Issue by gfvioli** [jmbuhr/otter.nvim#138]
I'm doing the most basic installation of quarto possible, like this:

![image](https://github.com/jmbuhr/otter.nvim/assets/96206151/f831d998-463d-4374-b308-8372482a67b4)

This is producing the following error message:

![image](https://github.com/jmbuhr/otter.nvim/assets/96206151/f27b82a3-f986-4c3b-9a0c-87a4723c0322)

Additionally, as soon as I add a quarto.lua file in my plugins directory (I'm using Lazy), the commnad `:Mason` produces the following error: 
![image](https://github.com/jmbuhr/otter.nvim/assets/96206151/1700b51d-dadc-4c46-9637-a85e1ba06bd2)

Any ideas what might be going on?

**Comment by jmbuhr** [comment]
otter.nvim is attaching language servers to buffers created behind the scenes that correspond to one for each type of code chunk in your quarto document (e.g. R, python etc.). That means, if one of those is not configured correctly you will also get an error. Do you get the same error when you just have a file of that type (R, python etc.)?

**Comment by jmbuhr** [comment]
I'm going to need a little more information, especially because the error doesn't get raised from one of my plugins, but rather by `mason`.

**Comment by gfvioli** [comment]
I'm more than happy to give you the information, I just don't know what you need. I'm early into my Neovim journey and not really sure I understand what's going on to be able to judge by myself what information do you need.

**Comment by jmbuhr** [comment]
I'd suggest starting your search in the file where the error message says the error is (this can of course be misleading, but is usually a good starting point).
