### ISSUE TITLE
Formatting Issues Using 'otter'.ask_format() in python

### ISSUE THREAD

**Issue by 00y300** [jmbuhr/otter.nvim#140]
We started setting up Quarto within my neovim config. 
I can make my auto-completion work as well. The problem is that if I were to test the auto format within a Python code chunk, it would give me an error. I can, of course provide more details. 
Quarto. lua
return {
	"quarto-dev/quarto-nvim",
	opt = {},
	dependencies = {
		"jmbuhr/otter.nvim",
	},
	config = function()
		vim.keymap.set({ "n", "i" }, "<leader>ci", "<esc>i```{python}<cr>```<esc>O", { desc = "[i]nsert code chunk" })
	end,
}

Error: 
   Error  16:32:49 notify.error method textDocument/rangeFormatting is not supported by any of the servers registered for the current buffer

![image](https://github.com/jmbuhr/otter.nvim/assets/72098565/61741582-213e-41be-b5b5-a51878dbab83)

**Comment by jmbuhr** [comment]
Do you have a language server for python that supports formatting?

**Comment by 00y300** [comment]
<img width="1428" alt="image" src="https://github.com/jmbuhr/otter.nvim/assets/72098565/525b8791-2bd1-47e5-8b0f-4df93e04671b">
@jmbuhr 
yes I do they do work in regular python files just not in the python code chunks.

**Comment by 00y300** [comment]
Here is my log file for my conform.log which is how I manage my formatters

Log file: /Users/00y300/.local/state/nvim/conform.log

Formatters for this buffer:
<none>

Other formatters:
black ready (python) /Users/00y300/.local/share/nvim/mason/bin/black
clang-format ready (cpp) /Users/00y300/.local/share/nvim/mason/bin/clang-format
gersemi ready (cmake) /Users/00y300/.local/share/nvim/mason/bin/gersemi
prettier ready (javascript, yaml, json, html, css, typescriptreact, javascriptreact, typescript) /Users/00y300/.local/share/nvim/mason/bin/prettier
stylua ready (lua) /Users/00y300/.local/share/nvim/mason/bin/stylua

**Comment by jmbuhr** [comment]
`black` is not a language server, it operates on (pure python) files by itself. But conform has options for handling embedded code that you might want to look into.

**Comment by 00y300** [comment]
Sorry I misinterpreted, yes, I do have a python language server. 
<img width="1222" alt="image" src="https://github.com/jmbuhr/otter.nvim/assets/72098565/b0510663-482f-40f4-b623-1b758c0e119d">
I am getting auto completions as well.

**Comment by 00y300** [comment]
I'm not sure if this will be helpful to anyone, but I found a solution and wanted to share the code for those using [conform.nvim](https://github.com/stevearc/conform.nvim) with the pyright LSP. This code is also useful for anyone looking to format their code using Black or other formatters. 

Here is the code I used in order to do Range/Injected Formatting:

```lua
return {
    "stevearc/conform.nvim",
    event = { "BufReadPre", "BufNewFile" },
    config = function()
        local conform = require("conform")

        conform.setup({
            formatters_by_ft = {
                lua = { "stylua" },
                python = { "black" }, -- Define the formatter for python
                quarto = { "injected" }, -- Use injected formatter for Quarto files
            },
            format_on_save = {
                lsp_fallback = true,
                async = false,
                timeout_ms = 1000,
            },
        })

        -- Injected language formatting setup
        conform.formatters.injected = {
            options = {
                ignore_errors = false,
                lang_to_ext = {
                    python = "py",
                },
                lang_to_formatters = {
                    python = { "black" }, -- Define the formatter for python
                },
            },
        }

        -- Set keymap for formatting file or range in visual mode
        vim.keymap.set({ "n", "v" }, "<leader>mp", function()
            conform.format({
                lsp_fallback = true,
                async = false,
                timeout_ms = 1000,
            })
        end, { desc = "Format file or range (in visual mode)" })
    end,
}
