### ISSUE TITLE
Broken syntax highlighting

### ISSUE THREAD

**Issue by akthe-at** [jmbuhr/otter.nvim#147]
OS: Windows 10
Neovim version: 0.10.0

Otter.nvim: (Latest but I did a bisect as well)

With the new release(s) of otter.nvim something seems to have broken with my .qmd file highlights, regardless of the language within the code chunks. It seems like commit 4d6c3355 is the first where this occurs.

![image](https://github.com/jmbuhr/otter.nvim/assets/105152139/4a19e8eb-8392-4876-8fb4-dbe9241cd4d7)

Hover/attaching/etc all seem to be working just fine, but not the syntax highlighting. 

![image](https://github.com/jmbuhr/otter.nvim/assets/105152139/bc120780-b197-4757-9986-8b181fcd4d03)

You can see the hover documentation works and looks just fine as well.
![image](https://github.com/jmbuhr/otter.nvim/assets/105152139/6ec254d0-71bf-4602-a58f-78b546c9d6f3)

(Also, in the new documentation for the lazy.nvim setup...should the dev = true be in the docs? Doesn't that try to install a local development plugin?)

Love and appreciate all your work, thank you!

**Comment by jmbuhr** [comment]
thanks, fixed the readme.
The highlighting I don't understand, otter.nvim doesn't do highlighting, that's treesitter. Though I also recently had updates in nvim-treesitter that required me to reinstall the markdown grammars. Maybe the same for you?

**Comment by akthe-at** [comment]
I have the markdown grammars installed already, it's strange indeed and I don't quite understand it either. It's breaking my obsidian.nvim rendering as well. If I disable otter everything works normal, and if I revert to pre otter 2.0 it works. I'm out on a walk with my dog so it's not easy to check but I'm wondering if I have old tree sitter queries related to code blocks that were rendered unneeded by the New TS changes or by otter changes

**Comment by akthe-at** [comment]
@jmbuhr idk if it was the changes to quarto.nvim or otter.nvim but this is now fixed, thanks! I am stoked about the change to otter acting as an lsp, great idea btw.
