### ISSUE TITLE
Noice Issues After updating Otter.NVIM

### ISSUE THREAD

**Issue by 00y300** [jmbuhr/otter.nvim#148]
Hey @jmbuhr 
I recently updated the Otter and removed it from sources in the nvimCmp. 
But Noice.nvim  has given me an issue saying this. 

This issue didn't happen before the update,but maybe it's more of a noise than Otter. Do you have any thoughts or suggestions on how I can look into this? 
Here is the file, and it is on line 106: https://github.com/folke/noice.nvim/blob/main/lua/noice/lsp/signature.lua
![image](https://github.com/jmbuhr/otter.nvim/assets/72098565/a10314f8-37dc-4b42-b9f3-dbe7fda10a57)

**Comment by jmbuhr** [comment]
I have a suspicion that I can look into. Otter now does indeed also handle the signature help lsp request, but I may not have configured it correctly to tell that it does on initialization. I'll check the lsp specification.

**Comment by 00y300** [comment]
@jmbuhr 
It does seem that by setting the version to v1.15.1, Noice does not give me an error.

**Comment by jmbuhr** [comment]
Did that solve it?

**Comment by 00y300** [comment]
> Did that solve it?

Yes this did solve it 
!!
