### ISSUE TITLE
failed to run config for otter.nvim

### ISSUE THREAD

**Issue by hopezh** [jmbuhr/otter.nvim#157]
I got the following error while installing my nvim config [here](https://github.com/hopezh/oatVim06): 

<img width="1450" alt="Screenshot 2024-07-06 at 11 22 30 PM" src="https://github.com/jmbuhr/otter.nvim/assets/23435810/6597c91b-3940-486d-8a44-f0a390227891">

May I ask what this means?

**Comment by jmbuhr** [comment]
This line was missing a couple of commits earlier, but should be there in the latest. So you probably just have to update otter.nvim.
https://github.com/jmbuhr/otter.nvim/blob/66b3a33735eda2f28025ac2f55c77faf9d1b4b68/lua/otter/lsp/handlers.lua#L4

**Comment by jmbuhr** [comment]
Sorry for the confusion, it's not the plugin that was outdated, it's a variable that's only available from Neovim v0.10 onward.
