### ISSUE TITLE
Add to mason?

### ISSUE THREAD

**Issue by catanzaromj** [jmbuhr/otter.nvim#160]
Hey! Thanks for the great plugin!

Is there any chance of getting this on the mason registry? It might add to the visibility of the project and make installing easier for new users.

**Comment by jmbuhr** [comment]
No need. Mason is for installing external tools, while this is still just a plugin (that happens to use the LSP and acts as a server, but it's still just a lua plugin)

**Comment by catanzaromj** [comment]
It's installing fine but I am having other issues. I will open another issue for that. As I was attempting to debug the problem, I realized that all of my other LSPs are installed via mason and "otter-ls" was installed as a plugin, as you mentioned.
