### ISSUE TITLE
Opening a blank file produces "Error requesting document symbols"

### ISSUE THREAD

**Issue by catanzaromj** [jmbuhr/otter.nvim#161]
I'm not sure when or why this problem started (so `otter.nvim` might be the wrong place for this issue). 

When I open a blank `test.qmd` file, I get a warning message: "Error requesting document symbols". I'm running neovim 0.10.0., otter.nvim 2.2.0 and quarto-nvim on commit 30298f7. I didn't have any issues the last time I edited `.qmd` files a couple weeks ago.

Thanks for any help you can provide.

**Comment by jmbuhr** [comment]
Good catch, Otter was always starting the language server even if no code cells were in the the document. And the language servers tells Neovim that it can get document symbols from it, but of course if there are no code cells there are no symbols to report.

**Comment by catanzaromj** [comment]
Unfortunately, I just realized I get the same error when opening a file that is not empty.

**Comment by jmbuhr** [comment]
That is expected (in a way), but shouldn't be a problem, just a warning. The explanation is for this is here: https://github.com/jmbuhr/otter.nvim?tab=readme-ov-file#paramsotterlang

**Comment by catanzaromj** [comment]
Thank you @jmbuhr for all the quick responses. That makes total sense.

After updating and restarting, I now get the following error on startup 

```Error detected while processing BufNewFile Autocommands for "*":                                                                                              
Error executing lua callback: .../Apps/nvim-linux64/share/nvim/runtime/filetype.lua:24: Error executing lua: .../Apps/nvim-linux64/share/nvim/runt
ime/filetype.lua:25: BufNewFile Autocommands for "*"..FileType Autocommands for "*"..function <SNR>1_LoadFTPlugin[19]..../.local/s
hare/nvim/lazy/quarto-nvim/ftplugin/quarto.lua: Vim(runtime):E5113: Error while calling lua chunk: ...al/share/nvim/lazy/otter.nvim/lua/otter/lsp/handlers.lua
:28: attempt to index local 'ms' (a nil value) 
```
I can open another issue if you'd like. I was hoping this would be another easy fix.

**Comment by jmbuhr** [comment]
Are you sure this is in fact updated? Because that local variable is loaded at the top of the file:
https://github.com/jmbuhr/otter.nvim/blob/cf97d2039f1b7295ffead93a1dbb2a65bab50fce/lua/otter/lsp/handlers.lua#L4

**Comment by jmbuhr** [comment]
Curiously, I got the same report already https://github.com/jmbuhr/otter.nvim/issues/157, so I wonder what causes two people to have the same outdated version.

**Comment by jmbuhr** [comment]
And it should have already been there on the version you mentioned: https://github.com/jmbuhr/otter.nvim/blob/5f03444012b44f3715413f51b47ba2b3607cd1be/lua/otter/lsp/handlers.lua#L4

Happy about any hints.

**Comment by catanzaromj** [comment]
Yea, I saw that issue. Previously, I was getting the same error message as #157's screenshot. Then I updated and now I'm getting a seemingly different error. Notice the line number has changed from `handlers.lua:15` to `handlers.lua:28`.

Mason shows version 2.2.1, and I even manually checked the file in mason's install path. Then I just purged otter.nvim and then re-installed it, and still the same error...

I just noticed a bit more though. First, the above error arises. Then I press enter and a second error follows it:
```
Error detected while processing BufReadPost Autocommands for "*":                                                                                             
Error executing lua callback: .../Apps/nvim-linux64/share/nvim/runtime/filetype.lua:24: Error executing lua: .../Apps/nvim-linux64/share/nvim/runt
ime/filetype.lua:25: BufReadPost Autocommands for "*"..FileType Autocommands for "*"..function <SNR>1_LoadFTPlugin[19]..script /home/michael.catanzaro/.local/
share/nvim/lazy/quarto-nvim/ftplugin/quarto.lua: Vim(runtime):E5113: Error while calling lua chunk: .../.local/share/nvim/lazy/quarto-nvim/lua/quarto/init.lu
a:108: loop or previous error loading module 'otter'                                                                                                          
stack traceback:                                                                                                                                              
        [C]: in function 'require'                                                                                                                            
        ...o/.local/share/nvim/lazy/quarto-nvim/lua/quarto/init.lua:108: in function 'activate'                                                               
        ...o/.local/share/nvim/lazy/quarto-nvim/ftplugin/quarto.lua:7: in main chunk                                                                          
        [C]: in function 'nvim_cmd'                                                                                                                           
        .../Apps/nvim-linux64/share/nvim/runtime/filetype.lua:25: in function <.../Apps/nvim-linux64/share/nvim/runtime/filetype.lua:24>          
        [C]: in function 'nvim_buf_call'                                                                                                                      
        .../Apps/nvim-linux64/share/nvim/runtime/filetype.lua:24: in function <.../Apps/nvim-linux64/share/nvim/runtime/filetype.lua:10>          
        [C]: at 0x64b586e94820                                                                                                                                
stack traceback:                                                                                                                                              
        [C]: in function 'nvim_cmd'                                                                                                                           
        ...Apps/nvim-linux64/share/nvim/runtime/filetype.lua:25: in function <.../Apps/nvim-linux64/share/nvim/runtime/filetype.lua:24>          
        [C]: in function 'nvim_buf_call'                                                                                                                      
        .../Apps/nvim-linux64/share/nvim/runtime/filetype.lua:24: in function <.../Apps/nvim-linux64/share/nvim/runtime/filetype.lua:10>          
        [C]: at 0x64b586e94820                                                                                                                                
stack traceback:                                                                                                                                              
        [C]: in function 'nvim_buf_call'                                                                                                                      
        .../Apps/nvim-linux64/share/nvim/runtime/filetype.lua:24: in function <...anzaro/Apps/nvim-linux64/share/nvim/runtime/filetype.lua:10>          
        [C]: at 0x64b586e94820                                                                                                                                
```
It seems like the second message is caused by the first, but maybe something there will help.

**Comment by jmbuhr** [comment]
wait, Mason? You mean lazy.nvim, right?

**Comment by catanzaromj** [comment]
Ahh yes, I'm sorry I should have written lazy.nvim.

**Comment by jmbuhr** [comment]
maybe it got confused about what version is installed? Can you just manually remove it and have it re-installed?
e.g. `rm -rf ~/.local/share/nvim/lazy/otter.nvim/`

**Comment by jmbuhr** [comment]
Also, close all running instances of nvim when you do that, just in case

**Comment by jmbuhr** [comment]
And can you actually inspect the files in the space where lazy puts them to check that they are actually the correct version? Like the handlers.lua file about which it complains, or the CHANGELOG.md file to see the version number.

**Comment by catanzaromj** [comment]
Closed everything, executed the `rm` command, still no luck. Manually inspecting `handlers.lua` and the `CHANGELOG.md` file in `~/.local/share/nvim/lazy/otter.nvim/` as output by `lazy`, and they look good. :confused:

**Comment by jmbuhr** [comment]
what does your lazy.nvim plugin spec for otter look like?

**Comment by jmbuhr** [comment]
The only other idea I have so far is to completely refresh by removing `~/.local/share/nvim` and `~/.local/state/nvim` to force lazy (and mason) to re-install all plugins and other tools.

**Comment by catanzaromj** [comment]
My lazy.nvim plugin spec for otter is minimal (copied from the repo README). I tried doing everything to force a re-install of all plugins. Still no luck. Is there any other cache I can remove?

**Comment by jmbuhr** [comment]
If nvim is closed, not as far as I know.

**Comment by jmbuhr** [comment]
So just this?
```
{
    'jmbuhr/otter.nvim',
    dependencies = {
      'nvim-treesitter/nvim-treesitter',
    },
    opts = {},
},
```

**Comment by jmbuhr** [comment]
Maybe just the classic "turn it (the computer) off and on again"... maybe there is an nvim process still running in the background somewhere that keeps a cache of an old otter.nvim version.

**Comment by jmbuhr** [comment]
Is your config available somewhere?

**Comment by catanzaromj** [comment]
Yes, exactly that config. 

It's weird that the error occurs on the correct line (28) for this version. Is it possible that something on line 4 is not defined, resulting in a nil value? 
https://github.com/jmbuhr/otter.nvim/blob/5f03444012b44f3715413f51b47ba2b3607cd1be/lua/otter/lsp/handlers.lua#L4

**Comment by catanzaromj** [comment]
I really do appreciate all your help in this. I've tried turning off and back on again. No, config is not available. I'm using astronvim, but other than that, it's pretty bare bones.

**Comment by jmbuhr** [comment]
Oh, my, yes! Why didn't I think of that? What version of Neovim are you on?

**Comment by jmbuhr** [comment]
It's only available from v0.10 onward!
https://github.com/neovim/neovim/blob/dfe19d6e0047ea2a2a75dff0c57f4c4de1c0196a/runtime/doc/news.txt

**Comment by jmbuhr** [comment]
Sorry for the confusion.

**Comment by catanzaromj** [comment]
I was on 0.9.5. Updating to 0.10 works!! Thank you so much for all your help. I feel like I owe you a coffee or a PR or something. Let me know how I can help out, and thanks again.

**Comment by jmbuhr** [comment]
Well thank you for sticking with me for finding the issue! :)

**Comment by olssonks** [comment]
I am using the latest Neovim release and still getting this `Error requesting document symbols` with Quarto. I get the error just working with [tutorial `hello.qmd` file](https://quarto.org/docs/get-started/hello/neovim.html#render-and-preview).

```
:verbose version

NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1725453128

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.10.1/share/nvim"
```

I am also using AstroNvim. I get the error for a somewhat minimal config with the [isolated installation](https://docs.astronvim.com/reference/alt_install/#isolated-installation) and only enabling the `astrolsp`, `mason`, and `none-ls`, and the basic `lazy.nvim` [Quarto specs](https://github.com/quarto-dev/quarto-nvim?tab=readme-ov-file#setup).

**Comment by jmbuhr** [comment]
The reason for this is probably different from op, but I suspect you have some form of statusline that wants to display document symbols and errors out when the first language server it asks doesn't provide them. See https://github.com/jmbuhr/otter.nvim?tab=readme-ov-file#paramsotterlang

**Comment by brettc** [comment]
In case anyone else ends up here. I was getting this same notification. I'm using astrovim, which pulls in aerial.nvim by default. Here is the fix that worked for me (which tracks @jmbuhr comment above). 

Put this in `.config/nvim/lua/plugins/aerial.lua`

```lua
---@type LazySpec
return {
  "stevearc/aerial.nvim",
  opts = function(_, opts)
    local default_backends = opts.backends or { "lsp", "treesitter", "markdown", "man" }
    if not vim.islist(default_backends) then
      default_backends = default_backends._ or { "lsp", "treesitter", "markdown", "man" }
    end

    -- In Quarto buffers, otter-ls advertises documentSymbolProvider but generic
    -- document-symbol requests need params.otter.lang to choose an embedded
    -- language. Aerial's LSP backend does not send that, so use Tree-sitter for
    -- the QMD outline and keep Otter available for normal embedded-code LSP use.
    opts.backends = {
      _ = default_backends,
      quarto = { "treesitter" },
      qmd = { "treesitter" },
    }
  end,
}
```
