### ISSUE TITLE
verbose.no_code_found = false does not work when entering buffer from a directory.

### ISSUE THREAD

**Issue by BirdeeHub** [jmbuhr/otter.nvim#163]
https://github.com/jmbuhr/otter.nvim/commit/dc90ffbc2e51839d88405cf38f75bdf172b798e7

^ this fix introduced an issue. It says turn verbose.no_code_found to false if you want to avoid the warning.

This works just fine if you open nvim directly into the file. The option stops it from warning.

But if you have otter.activate() on a filetype trigger, open nvim into a directory and THEN enter the file, it warns regardless of this option.

Highly annoying, please fix or remove the warning. At least it only happens once...

I have require('otter').activate(nil, true, true, nil) in an ftplugin file for the languages I want it to activate for, and it lazy loads before this is called, if this is relevant info.

**Comment by jmbuhr** [comment]
I can reproduce that. Need to rewrite config handling at some point, it interacts weirdly with lazy loading.

**Comment by BirdeeHub** [comment]
YAAAY ITS NOT A HEISENBUG!!!
