### ISSUE TITLE
Completion does not work, even on a minimal configuration

### ISSUE THREAD

**Issue by fasterius** [jmbuhr/otter.nvim#17]
First, thanks for the awesome plugin - both `otter.nvim` and `quarto-nvim`! Really love the idea and how it works, but I'm having issues with getting the completion to work. I've spent more time troubleshooting now than I care to admit, and I cannot for the life of me get it to work. Completion in other filetypes (_e.g._ R, Python, R Markdown) works just fine, it's just Quarto that doesn't work.

Both plugins (`quarto-nvim` and `otter.nvim`) load just fine, I get syntax highlighting from Treesitter and I can correctly see active but not attached LSP clients when I look at `LspInfo`. I can move to the otter-buffers, within which completion works just fine - the sources are just the normal ones, though, and not otter sources (which I assume is correct in these buffers). There's just no connection between Otter and `nvim.cmp`, even though I've checked that I'm using all the correct configurations for all the related plugins (following your documentation). LSP-related things like goto-definition still works inside Quarto files, though.

Thinking that it was probably something weird I have in my config I setup a minimal configuration with just `nvim.cmp`, `nvim.lspconfig`, `nvim-treesitter`, `quarto-nvim` and `otter.nvim`, but it still doesn't work. The config is here: https://github.com/fasterius/nvim-otter-minimal.

I'm probably missing something stupid, but I can't for the life of me figure out _what_. Any ideas?

**Comment by jmbuhr** [comment]
With your minimal configuration I noticed that indeed I don't get code completion right after opening the file, but it works fine after having used e.g. `K` to show the documentation once.
(I had to disable marksman because I don't have it installed on this machine).
![image](https://user-images.githubusercontent.com/17450586/216305502-2c7dd407-71f1-447b-bce9-a04c620e4964.png)

Can you confirm that this is the same for you? And can you also try it with the official kickstarter configuration: https://github.com/jmbuhr/quarto-nvim-kickstarter?

**Comment by fasterius** [comment]
I can confirm that the minimal config works after using `K`. It also works using the `quarto-nvim-kickstarter`, even without having to use `K` before. I did try this earlier, actually, but the kickstarter does _not_ work inside Conda environments (even when I disable Mason to not auto-install anything and just use manually installed LSPs inside the Conda environments).

The Conda-problem was actually what lead me to start troubleshooting - I'm basically inside a Conda environment 100% of the time, so that's a must-have-functionality for me. When I started troubleshooting I couldn't even get Otter working outside of Conda, so I figured "one thing at a time", hence me not mentioning this before.

**Comment by jmbuhr** [comment]
Interesting, I have also tried it in a conda enviroment and it works for me, specifically with mason. Do you maybe have some things installed in the enviroment, like lsp servers, that shadow the lsp servers by mason?

What does the output of `:LspInfo` and `CmpStatus` look like in a fully loaded qmd file with e.g. R code chunks?

**Comment by jmbuhr** [comment]
Conda is pretty notorious for these sorts of things...

**Comment by jmbuhr** [comment]
Another Idea if have specifically for R: When using the `renv` package for an isolated enviroment I have to install the r language server in there as well. Maybe you have something similar going on.

**Comment by jmbuhr** [comment]
So it looks like this is another, not an otter, problem ;)

**Comment by fasterius** [comment]
Okay, then I'd be very interesting to know how to set that up, since all I'm getting when using Mason in a Conda environment are things like `Client 1 quit with exit code 1 and signal 0` when an LSP is started :-/ I have tried to both have and not have language servers inside Conda with Mason and the results are the same. Since it never worked _at all_ while not using Mason and installing them manually worked for everything except Otter that's what I ran with.

Here are some screenshots, both from the minimal config and my full config:

`LspInfo` (minimal config)
![Screenshot 2023-02-02 at 15 31 59](https://user-images.githubusercontent.com/12528765/216352630-412aa538-b239-424e-8400-fb7aab542549.png)

`LspInfo` (my full config):
![Screenshot 2023-02-02 at 15 23 00](https://user-images.githubusercontent.com/12528765/216350441-eea2ed52-cc05-4a6a-9934-83c2bf2920d3.png)

`CmpStatus` (minimal config, before `K`):
![Screenshot 2023-02-02 at 15 29 49](https://user-images.githubusercontent.com/12528765/216352172-c8186055-e2ca-477d-bf1b-bcec10a86028.png)

`CmpStatus` (minimal config, after `K`):
![Screenshot 2023-02-02 at 15 28 40](https://user-images.githubusercontent.com/12528765/216351895-f87c8d25-bf87-40ac-b407-c295915dcaf2.png)

`CmpStatus` (my full config, regardless of `K`):
![Screenshot 2023-02-02 at 15 23 46](https://user-images.githubusercontent.com/12528765/216350623-371f081f-f872-48a0-a768-ad25031eaac0.png)

So, the `otter` source is somehow not being recognised at various stages?

**Comment by jmbuhr** [comment]
LspInfo tells you where the logfile for your language servers is. This may tell you why the language server crashes in a conda environment.

**Comment by jmbuhr** [comment]
Also note that the otter source is by design only available when your cursor is inside of a code chunk.

**Comment by fasterius** [comment]
Okay, I have no idea why it works now, but after switching back-and-forth between the configs a bit it just works now, both outside and inside Conda environments! I only get completion like a third of the time without doing `:LspInfo`, but after doing that it seems to work! Using `K` only worked most of the time, for some reason, while `:LspInfo` worked all of the time. I also tried waiting a long time before going into insert mode to see if it was some kind of loading-related issue, but it didn't make any difference.

I'm real sorry for taking up your time! 😓 I don't know why it works now, but it does - having to type `:LspInfo` once before starting some coding is slightly annoying, but it's an annoyance I can live with. No idea whether that particular weirdness if related to `nvim-cmp`, `lsp-config`, `quarto-nvim` or `otter.nvim` 😅

**Comment by jmbuhr** [comment]
Ok. There may still be a lessen here about when the lsp server starts up and when the client attaches and I may find a solution to make sure it starts up a small while before you actually need it. Do let me know if you find something!

**Comment by fasterius** [comment]
Will do!
