### ISSUE TITLE
Treat pyodide blocks as python in quarto

### ISSUE THREAD

**Issue by JJJHolscher** [jmbuhr/otter.nvim#170]
Recently [quarto-live](https://github.com/r-wasm/quarto-live) came out, which allows `pyodide` blocks to be run in the browser through webassembly.
Pyodide is just mostly a subset of python, but otter does not recognize it as such (I get no highlighting).
I'd like for Pyodide blocks to just be treated as python.
My current workflow is to just type in ` '''{python} ` instead of ` '''{pyodide} ` during most of my editing and then change it back to `pyodide` when I need to render.

The same would probably go for the new `webr` block for interactive r code, though I don't use or touch that.

If you don't want to add this to otter, I can imagine that it is fairly easy for me to then fix this just on my end. In which case I'd appreciate any pointers for doing that.

**Comment by jmbuhr** [comment]
It's a two-step fix: First, we map the pyodide and webr extensions to the regular python and R filetypes to get normal highlighting in quarto and standalone files. This is something you have to do in your config, here is how I just did that: https://github.com/jmbuhr/quarto-nvim-kickstarter/commit/e724b4cff24a4002090244198ccb96b3d7d48313

Secondly, we need to add the extensions to otter, which I just did :) https://github.com/jmbuhr/otter.nvim/pull/171
So now it should work.
