### ISSUE TITLE
Error on `:lua require'otter'.activate()` Invalid 'group': 'lspconfig'                                                  

### ISSUE THREAD

**Issue by kusnezoff-alexander** [jmbuhr/otter.nvim#175]
When executing `:lua require'otter'.activate()` I get the following error:
```
E5108: Error executing lua .../.local/share/nvim/lazy/otter.nvim/lua/otter/init.lua:157: Invalid 'group': 'lspconfig'                                                  
stack traceback:                                                                                                                                                          
        [C]: in function 'nvim_get_autocmds'                                                                                                                              
        ....local/share/nvim/lazy/otter.nvim/lua/otter/init.lua:157: in function 'activate'                                                                           
        [string ":lua"]:1: in main chunk
```

The line referenced in the error msg: `local autocommands = api.nvim_get_autocmds({ group = "lspconfig", pattern = lang })`

Am I missing a dependeny here or where is the autogroup `lspconfig` defined?

**Comment by jmbuhr** [comment]
See `set_filetype` in https://github.com/jmbuhr/otter.nvim?tab=readme-ov-file#configure-otter.
Do you configure auto-starting of your language servers manually? Or did lspconfig change their autocommand, in which case otter needs changes?

**Comment by kusnezoff-alexander** [comment]
@jmbuhr Setting `set_filetype=true` did the trick, thank you.
