### ISSUE TITLE
Multiple languages in a single org file

### ISSUE THREAD

**Issue by refaelsh** [jmbuhr/otter.nvim#176]
I manage my `configuration.nix` in a single org file and using this plugin for org: https://github.com/nvim-orgmode/orgmode.
When I execute `:lua require("otter").activate()`, I see that Nix language server is being activated.
I also have several `/*lua*/` in my org file inside a Nix source code block.
1. Why Nix and not any other language that is present in the org file?
2. How it decides which LSP to activate in case of an org file with multiple languages?
3. Maybe scan the entire org file and activate all appropriate languages from source code blocks and from `/*lua*/ blocks?

**Comment by jmbuhr** [comment]
otter activates all languages that are found via injection querries, so as a rule of thumb, if the language is correctly highlighted with treesitter it should appear as an otter buffer. See https://github.com/jmbuhr/otter.nvim?tab=readme-ov-file#activate-otter

**Comment by jmbuhr** [comment]
I see. Otter does not currently support nested injections.

**Comment by refaelsh** [comment]
> I see. Otter does not currently support nested injections.

I understand. Is that decision by design? Or it just happens that nobody proposed that kind of feature?

**Comment by jmbuhr** [comment]
I suspect it's a very niche feature, so it just hasn't come up. If there is an implementation of this that doesn't compromise maintainability and performance for the non-nested case I would be happy about a PR, though.

**Comment by refaelsh** [comment]
It is indeed a niche feature. I just thought I'd ask anyway. Thank you for the answer, I understand.
