### ISSUE TITLE
How to use with bash multiline string?

### ISSUE THREAD

**Issue by PerchunPak** [jmbuhr/otter.nvim#185]
How to use it with this example?

```bash
cat >/tmp/hello.json << EOF
{"a": "b"}
EOF
```

That's probably should be added to https://github.com/jmbuhr/otter.nvim/tree/main/tests/examples

**Comment by jmbuhr** [comment]
nvim-treesitter already has an injection for heredocs, but you need to use the delimiters to specify the language, see https://github.com/nvim-treesitter/nvim-treesitter/blob/c50981479e4271ec87c5a15ec991472bdec4f1b8/queries/bash/injections.scm#L7-L10

once you have injections, otter can work.

You know your injections are working when you get syntax highlighting for the heredoc body, e.g.
![image](https://github.com/user-attachments/assets/c0aae956-be57-4f8f-a573-d4a767f7287a)

**Comment by PerchunPak** [comment]
That's... not something I would expect, but thanks!

**Comment by jmbuhr** [comment]
How do you expect nvim to infer the language of the heredoc? You can then write a query to implement that logic.
