### ISSUE TITLE
How to embed fragments within arbitrary filetypes?

### ISSUE THREAD

**Issue by rwmpelstilzchen** [jmbuhr/otter.nvim#187]
Markdown has built-in support for embedding fragments written in other languages, with the <code>```</code> syntax. This is a natural use case for Otter. However, it might be extremely useful to embed fragments within languages that don’t support this natively. For example, say we write a LaTeX document and want to plan the outline of a section using [Orgmode](https://github.com/nvim-orgmode/orgmode). It would be nice to have this supported in Otter:

```latex
\documentclass{article}

\usepackage{environ}
\NewEnviron{ignored}{}

\begin{document}
\section{Some complex topic}
hello

\begin{ignored}
BEGINFRAGMENT org
* A good idea
** Step A
** Step B
*** TODO Talk with Jane to see if this can be done
** DONE Show Luna a draft
* Another brilliant idea
ENDFRAGMENT
\end{ignored}

1234
\end{document}
```

If one could define arbitrary strings to initiate/terminate fragments of a certain type, it would be even better (then a custom `\begin{org}`/`\end{org}` environment can be used, and detected by Otter as boundaries of an Orgmode fragment, without the cumbersome `BEGINFRAGMENT org`/`ENDFRAGMENT`).

LaTeX supports ignoring parts of the file, as demonstrated above. For wider applicability of the proposed idea, comments have to be supported. For example:

```python
print("Hello world")
# BEGINFRAGMENT org
# * A fascinating idea as to how to improve this Python program
# ** Step A
# ** Step B
# ENDFRAGMENT
```

**Comment by jmbuhr** [comment]
If you can write a treesitter injection for it, otter will work out of the box.

**Comment by jmbuhr** [comment]
LaTeX currently has these injections, assuming you use nvim-treesitter: https://github.com/nvim-treesitter/nvim-treesitter/blob/046b8e936142ca7d0285c807201965ae4916bf01/queries/latex/injections.scm
The last of which appears to already support arbitrary languages: https://github.com/nvim-treesitter/nvim-treesitter/blob/046b8e936142ca7d0285c807201965ae4916bf01/queries/latex/injections.scm#L32-L36, but I'm not sure what a `minted_environment` is. You could expand upon this.

**Comment by rwmpelstilzchen** [comment]
Thank you for the prompt and useful reply (and for Otter, and for your videos… 🙂🌼🙏)!

Do you happen to know whether it’s possible to have plugin support for the injections, or is it limited to LSP, completion and snippets? Like [nvim-orgmode](https://github.com/nvim-orgmode/) keymaps for `org` injections (`\begin{minted}{org} […] \end{minted}`).

> I'm not sure what a minted_environment is

[minted](https://ctan.org/pkg/minted) is a LaTeX package for source code highlighting.

**Comment by jmbuhr** [comment]
Interesting idea. what do you mean by plugin support? Not generally, Neovim treats one buffer as one filetype, hence the necessity of otter. For keymaps you'd have to build something custom, with each keymap mapping to a function that first checks the current language context, e.g. with https://github.com/jmbuhr/otter.nvim/blob/ca9ce67d0399380b659923381b58d174344c9ee7/lua/otter/keeper.lua#L198 or something simpler, custom based on treesitter.

**Comment by rwmpelstilzchen** [comment]
> what do you mean by plugin support?

Some plugins provide special functionality for certain filetypes. For example, in the case of `.org` files mentioned above [nvim-orgmode](https://github.com/nvim-orgmode/) allows cycling todo status (like changing `TODO` to `DONE` when the cursor is somewhere under the immediate heading and the user hits `cit`), (pro/de)moting subtrees (`<s`/`>s`), inserting scheduled date with a calendar interface (`<Leader>ois`) and many other features that make working with org files in NeoVim feel not like manually editing a text file but having a fully-fledged productivity system at your fingertips; [org-bullets.nvim](https://github.com/nvim-orgmode/org-bullets.nvim) and [headlines.nvim](https://github.com/lukas-reineke/headlines.nvim) improve the visual side of things greatly. These features are available with standalone org files, but not with org injections (fragments) within other files.
