### ISSUE TITLE
Blink support

### ISSUE THREAD

**Issue by stevenxxiu** [jmbuhr/otter.nvim#191]
<https://github.com/Saghen/blink.cmp> is a new completion plugin written in *Rust*. It's a lot faster than and replaces *nvim-cmp*.

It'd be nice to support *blink*, to give another option.

**Comment by jmbuhr** [comment]
Check out the note at the top of the readme, otter no longer comes with a dedicated nvim-cmp completion source. Instead it functions as an lsp server and as such works with blink out of the box! In fact, I have been using it with blink for a while now.

**Comment by Noghpu** [comment]
Any hint to how to get working? I tried to add something like
``` {lua}
return {
  {
    "saghen/blink.cmp",
    dependencies = {
      "jmbuhr/otter.nvim",
    },
    opts = {
      sources = {
        default = { "otter" },
        per_filetype = {
          quarto = { "otter" },
        },
      },
    },
  },
}
```
but blink throws an error. Am I missing something obvious?

**Comment by jmbuhr** [comment]
You don't need to add it as a source, otter is an lsp client-server combo, so its completions come with the builtin lsp source of blink. All you need to do is activate otter and you are good to go.
