### ISSUE TITLE
Feature request: support coq_nvim (or: be autocompletion-engine-agnostic)

### ISSUE THREAD

**Issue by neumannjan** [jmbuhr/otter.nvim#34]
Hi,

I love the plugin, but recently I switched away from nvim-cmp to [coq_nvim](https://github.com/ms-jpq/coq_nvim) due to performance reasons and unfortunately it seems that otter lacks support for coq.

Could support for coq please be added?

Alternatively, why not register a new LSP directly in neovim (in lua) which will simply redirect to other relevant LSPs, instead of having this implementation as a separate autocompletion plugin? I haven't looked into neovim APIs in great detail, but it seems that something along those lines should be possible.

Thanks again for the plugin and your time.

**Comment by jmbuhr** [comment]
I agree that a language server that performs essentially the functionality of `otter.nvim` (keep pure language buffers in sync, redirect requests) would be a very clean solution, though it is quite likely to find a bunch of edgcases in lsp and neovim api implementations that may make it less clean. However, I don't currently have the time to write a language server.

As for `coq`, it looks like a very promising approach and seems to also be extensible similar to `cmp`. I would be very happy about a PR to otter.nvim if you translate the `cmp` source there to `coq`.

**Comment by jmbuhr** [comment]
I will revisit this once https://github.com/neovim/neovim/pull/24338 or something along those lines is merged. This should make it easier to turn `otter.nvim` essentially into a language server with the necessary translations included.
