### ISSUE TITLE
Readme improvements

### ISSUE THREAD

**Issue by LamprosPitsillos** [jmbuhr/otter.nvim#69]
It would be greatly appreciated if the README was a bit more detailed . With some added installation instructions and how to use .

For example:  
> Assuming otter.nvim is configured and added to nvim-cmp as a completion source

These are never mentioned and the only docs is the README

> require'otter'.activate({'python', 'r', <more languages you want to embed> })

Should this be called like `.setup()` or should this be called on file enter with all the languages the file is potentially going to have ?

and a few other stuff.

Thanks for your hard work!

**Comment by gzagatti** [comment]
Recently I have become interested in Otter. I've come up with a turnkey solution using Packer.

```lua
  use {
    'jmbuhr/otter.nvim',
    requires = { 'neovim/nvim-lspconfig' },
    config = function()
        function otter_extensions(arglead, _, _)
          local extensions = require'otter.tools.extensions'
          local out = {}
          for k, v in pairs(extensions) do
            if arglead == nil or k:find("^" .. arglead) ~= nil then
              table.insert(out, k)
            end
          end
          return out
        end
        vim.api.nvim_create_autocmd('FileType', {
          group = vim.api.nvim_create_augroup("lspconfig", { clear = false }),
          pattern = otter_extensions(),
          callback = function(ev)
            local buf = ev.buf
            local ft = vim.api.nvim_get_option_value("filetype", { buf = ev.buf })
            local matching_configs = require('lspconfig.util').get_config_by_ft(ft)
              for _, config in ipairs(matching_configs) do
                print("Activating ", config.name, " LSP in buffer ", buf, "...")
                config.launch(buf)
              end
          end
        })
        vim.cmd [[ command! -nargs=* -complete=customlist,v:lua.otter_extensions LspOtter lua require'otter'.activate({<f-args>}) ]]
    end
  }
```

Whenever you want to use Otter just call in the command line:

```
:LspOtter python
```

Any suggestions to improve the code are welcome. For some reason, the LSP activation is called twice. I haven't figured this out.
