### ISSUE TITLE
`get_language_lines_in_visual_selection` off by one

### ISSUE THREAD

**Issue by benlubas** [jmbuhr/otter.nvim#70]
if I have a code block like this:
```
```{python}
print("Hello")
x = 10
...
```

and call `otterkeeper.get_language_lines_in_visual_selection(true)` with the first line visually selected (visual or visual line mode) I get nil. 

So I think there is an off by one somewhere

**Comment by jmbuhr** [comment]
That is quite likely, I have gone through several iterations where I thought I'd fixed an off by one error only to get a different one. Like putting in an usb-stick, but worse. I'll have a look!
