### ISSUE TITLE
Turn keymaps off

### ISSUE THREAD

**Issue by JmyL** [jmbuhr/otter.nvim#71]
Hello!

I saw some key mappings on dev_setup function in init.lua file.
How can I turn these off without modifying otter's sources?

Thx.

**Comment by jmbuhr** [comment]
the dev setup is just for development and testing. The regular otter.setup and otter.activate functions don't set any keybindings.

**Comment by JmyL** [comment]
@jmbuhr I hope so, but my `gr` key is still replaced by the setting on dev_setup function.

![image](https://github.com/jmbuhr/otter.nvim/assets/2654044/77650c16-8ca5-41bf-86f0-71ac7a4418d6)

My lazy.nvim setup is like below. I set dev as false intensionally.

```
  {
    "jmbuhr/otter.nvim",
    dev = false,
    dependencies = {
      { "neovim/nvim-lspconfig" },
    },
    opts = {
      buffers = {
        set_filetype = true,
      },
    },
  },
```

**Comment by jmbuhr** [comment]
The dev keyword in lazy.nvim only refers to not using your own local version of the plugin, not a function in the plugin.

However, I see from your screenshot that you are using otter.nvim in the context of one of my other plugins, quarto-nvim. quarto-nvim does indeed set those keyboard shortcuts via its setup, but you can disable or remap them there.

**Comment by JmyL** [comment]
Thanks! It's cleared after defining new config function with calling `require("quarto").setup{...}` explicitly.
