### ISSUE TITLE
Hidden buffers sometimes include extra characters from source buffer

### ISSUE THREAD

**Issue by b0o** [jmbuhr/otter.nvim#72]
When injecting code like this in a TypeScript or JavaScript file:

```js
const vert = glsl`
  void main() {
    gl_Position = vec4(0.0, 0.0, 0.0, 1.0);
  }
`;

const foo = html`
  <div>
    <p>hello</p>
  </div>
`;

const bar = css`
  .foo {
    color: rgb(0, 0, 0);
  }
`;

const lua = lua`
  local foo = "bar"
  print(foo)
`;
```

I would not expect the backticks to be included, but they are:

![2023-12-01_18-46-05_region](https://github.com/jmbuhr/otter.nvim/assets/21299126/e93e3bb3-11a2-481b-b979-5f7ccef7c7c6)

This causes incorrect diagnostic errors with some LSPs, like luals.

**Comment by jmbuhr** [comment]
This is caused by https://github.com/jmbuhr/otter.nvim/issues/37#issuecomment-1579575794.
I need to revisit this and see if now there is a way to get the correct ranges with offsets from injections applied.

If this is still not possible, maybe we can work around this by defining a set of surrounding characters that we remove from all captured text by default.

**Comment by b0o** [comment]
I just opened an issue for a very similar bug in conform.nvim, perhaps the root cause is related: https://github.com/stevearc/conform.nvim/issues/229

**Comment by jmbuhr** [comment]
Looks like the same problem with the offset directive, indeed.

**Comment by jmbuhr** [comment]
I added the workaround for via https://github.com/jmbuhr/otter.nvim/pull/73 for now

**Comment by b0o** [comment]
Thanks for that! Just wanted to note that the PR did fix the diagnostics, but when running `otter.ask_format()`, the entire code block including 

```
const foo = glsl`
```

and everything on the closing ` line is replaced.

**Comment by jmbuhr** [comment]
hm, interesting point. All that otter does is redicrect lsp formatting responses from the hidden buffer to the main buffer. i.e. if the lsp wants to change a line in the otter buffer it would change the line in the main buffer instead, but it should do so within the range of its language injection. For now the PR only changed the `text` content, not the range, so I'll have to modify that as well when a wrapping quote has been removed.
