### ISSUE TITLE
FR: expose API for diagnostics refreshing / Bug: Diagnostics not update via `vim.cmd.write` etc

### ISSUE THREAD

**Issue by chrisgrieser** [jmbuhr/otter.nvim#81]
The FR part: 
Right now, the diagnostics only update on write. As far as I can tell, via the `BufWritePost` autocmd. When you are not in the habit of constantly saving, it is somewhat annoying often only show up much later.

--- 
The bug (?) part:
I tried to fix that via this autocmd, which for some reason saves the file but does not trigger the refreshing of diagnostics. Only manually typing `:w` seems to work 🤔 

```lua
vim.api.nvim_create_autocmd("FileType", {
	pattern = "markdown",
	callback = function(ctx)
		vim.api.nvim_create_autocmd("InsertLeave", {
			buffer = ctx.buf,
			callback = function() vim.cmd.write() end,
		})
	end,
})
```

**Comment by chrisgrieser** [comment]
Oh nice, I wasn't aware of `:doautocmd`. Thanks.

Unfortunately, `:doautocmd` does not work, just like `vim.cmd.write()` does not appear to work. It looks indeed like the two manual saves are required.

Maybe adding `BufReadPost` as autocmd event would at least help by displaying the diagnostics when you enter a new buffer?

**Comment by jmbuhr** [comment]
Good point, I'll experiment with more autocommands in general. Maybe the builtin diagnostics also have a hint as to when those are normally updated.
