### ISSUE TITLE
How to use this with eruby?

### ISSUE THREAD

**Issue by Bleksak** [jmbuhr/otter.nvim#84]
When writing *.html.erb, i would like to have <% %> blocks use solargraph LSP. 
Is it possible with this plugin? If so, how?

**Comment by jmbuhr** [comment]
Yes, you need a treesitter injection query to define those blocks as html (e.g. https://github.com/nvim-treesitter/nvim-treesitter/blob/e9602f41192ba51842b4be4d02c718a64cd57acf/queries/ruby/injections.scm) and then configure and activate otter (https://github.com/jmbuhr/otter.nvim?tab=readme-ov-file#use-otter).

In the nvim >= 0.10 you can play around with treesitter queries in `:lua vim.treesitter.inspect_tree()` by pressing `o` (see help page).
